version: '3'

services:
  app:
    build:
      context: .
    environment:
      - NODE_ENV=development
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=${DB_USER:-default_user}
      - DB_PASSWORD=${DB_PASSWORD:-default_password}
      - DB_NAME=${DB_NAME:-default_database}
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD:-root_password}
      - MYSQL_DATABASE=${DB_NAME:-default_database}
